=== mwdchang/lightly-rusted/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/scene.schema.json",
  "title": "Ray Tracer Scene",
  "type": "object",

  "properties": {
    "description": {
      "type": "string"
    },

    "environment": {
      "$ref": "#/$defs/environment"
    },

    "point_lights": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/pointLight"
      }
    },

    "materials": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/material"
      }
    },

    "root": {
      "$ref": "#/$defs/node"
    }
  },

  "required": [
    "environment",
    "point_lights",
    "materials",
    "root"
  ],

  "$defs": {
    "vec3": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 3,
      "maxItems": 3
    },

    "scalar": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 1,
      "maxItems": 1
    },

    "environment": {
      "type": "object",
      "properties": {
        "background": {
          "$ref": "#/$defs/vec3"
        },
        "ambient_light": {
          "$ref": "#/$defs/vec3"
        },
        "camera_position": {
          "$ref": "#/$defs/vec3"
        },
        "camera_target": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "background",
        "ambient_light",
        "camera_position",
        "camera_target"
      ]
    },

    "pointLight": {
      "type": "object",
      "properties": {
        "position": {
          "$ref": "#/$defs/vec3"
        },
        "intensity": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "position",
        "intensity"
      ]
    },

    "material": {
      "type": "object",
      "properties": {
        "albedo": {
          "$ref": "#/$defs/vec3"
        },
        "texture": {
          "type": "string"
        },
        "shine": {
          "type": "number"
        },
        "specular": {
          "type": "number"
        },
        "reflectivity": {
          "type": "number"
        },
        "transparency": {
          "type": "number"
        },
        "ior": {
          "type": "number"
        }
      },
      "required": [
        "shine",
        "specular",
        "reflectivity",
        "transparency",
        "ior"
      ],
      "oneOf": [
        {
          "required": ["albedo"]
        },
        {
          "required": ["texture"]
        }
      ]
    },

    "scaleTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "scale"
        },
        "value": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "translateTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "translate"
        },
        "value": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "rotateXTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate_x"
        },
        "value": {
          "$ref": "#/$defs/scalar"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "rotateYTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate_y"
        },
        "value": {
          "$ref": "#/$defs/scalar"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "rotateZTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate_z"
        },
        "value": {
          "$ref": "#/$defs/scalar"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "transform": {
      "oneOf": [
        {
          "$ref": "#/$defs/scaleTransform"
        },
        {
          "$ref": "#/$defs/translateTransform"
        },
        {
          "$ref": "#/$defs/rotateXTransform"
        },
        {
          "$ref": "#/$defs/rotateYTransform"
        },
        {
          "$ref": "#/$defs/rotateZTransform"
        }
      ]
    },

    "node": {
      "type": "object",
      "properties": {
        "transforms": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/transform"
          }
        },

        "mesh_id": {
          "type": "string"
        },

        "material_id": {
          "type": "number"
        },

        "children": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/node"
          }
        }
      }
    }
  }
}

=== mwdchang/lightly-rusted/examples/obj.json
{
  "description": "Object scene",
  "environment": {
    "background": [0.5, 0.5, 0.5],
    "ambient_light": [0.1, 0.1, 0.1],
    "camera_position": [0, 5, 10],
    "camera_target": [0, 2, -6],
    "shadows": true,
    "reflections": true,
    "refractions": true,
    "secondary_ray_eps": 0.008
  },
  "point_lights": [
    {
      "position": [5, 15, 15],
      "intensity": [1200.0, 1200.0, 1200.0]
    }
  ],
  "materials": [
    {
      "albedo": [0.7, 0.7, 0.7],
      "shine": 2000,
      "specular": 0.2,
      "reflectivity": 0.3,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.8, 0.8, 0.8],
      "shine": 0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.7,
      "ior": 1.09
    },
    {
      "albedo": [0.0, 1.0, 0.0],
      "shine": 0,
      "specular": 0.0,
      "reflectivity": 0.1,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.8, 0.8, 0.0],
      "shine": 0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.7,
      "ior": 0.92
    }
  ],
  "root": {
    "children": [
      {
        "transforms": [
          { "type": "scale", "value": [2.0, 2.0, 2.0] },
          { "type": "translate", "value": [0, 0, -6] }
        ],
        "children": [
          {
            "mesh_id": "teapot",
            "material_id": 1
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [4.0, 1.0, 0.5] },
          { "type": "rotate_x", "value": [0.3] },
          { "type": "translate", "value": [0, 5, -6] }
        ],
        "children": [
          {
            "mesh_id": "cube",
            "material_id": 3
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [0, 0, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [-2.5, -2, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [2.5, 2, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [5, 4, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [-5, -4, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [7.5, 6, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [1.0, 14.0, 1.0] },
          { "type": "translate", "value": [-7.5, -6, -20] }
        ],
        "children": [
          {
            "mesh_id": "cylinder",
            "material_id": 2
          }
        ]
      }

    ]
  }
}

=== mwdchang/lightly-rusted/examples/primitives.json
{
  "description": "Primitives",
  "environment": {
    "background": [0, 0.0, 0],
    "ambient_light": [0.1, 0.1, 0.1],
    "camera_position": [5, 7, 11],
    "camera_target": [0, 0, 0],
    "shadows": true,
    "reflections": false,
    "refractions": false,
    "secondary_ray_eps": 0.01
  },
  "point_lights": [
    {
      "position": [0, 8, 15],
      "intensity": [300.0, 300.0, 300.0]
    }
  ],
  "materials": [
    {
      "albedo": [0.9, 0.9, 0.9],
      "shine": 200,
      "specular": 0.5,
      "reflectivity": 0.4,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [1.0, 0.1, 0.1],
      "shine": 200,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.1, 1.0, 0.1],
      "shine": 200,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.5,
      "ior": 1
    },
    {
      "albedo": [0.1, 0.1, 1.0],
      "shine": 200,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [1.0, 1.0, 0.1],
      "shine": 200,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.1, 1.0, 1.0],
      "shine": 200,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    }
  ],
  "root": {
    "children": [
      {
        "transforms": [
          { "type": "scale", "value": [90.0, 0.05, 90.0] },
          { "type": "translate", "value": [0, -2, 0] }
        ],
        "children": [
          {
            "mesh_id": "cube",
            "material_id": 0
          }
        ]
      },
      {
        "transforms": [
          { "type": "translate", "value": [0, 0, 4] }
        ],
        "children": [
          {
            "transforms": [
              { "type": "scale", "value": [1.2, 1.2, 1.2] },
              { "type": "translate", "value": [-3, 0, 0] }
            ],
            "children": [
              {
                "mesh_id": "torus",
                "material_id": 1
              }
            ]
          },
          {
            "transforms": [
              { "type": "scale", "value": [1.2, 1.2, 1.2] },
              { "type": "translate", "value": [0, 0, 0] }
            ],
            "children": [
              {
                "mesh_id": "cube",
                "material_id": 2
              }
            ]
          },
          {
            "transforms": [
              { "type": "scale", "value": [1.2, 1.2, 1.2] },
              { "type": "translate", "value": [3, 0, 0] }
            ],
            "children": [
              {
                "mesh_id": "sphere",
                "material_id": 3
              }
            ]
          },
          {
            "transforms": [
              { "type": "scale", "value": [1.2, 1.2, 1.2] },
              { "type": "translate", "value": [-3, 0, -4] }
            ],
            "children": [
              {
                "mesh_id": "cone",
                "material_id": 4
              }
            ]
          },
          {
            "transforms": [
              { "type": "scale", "value": [1.2, 1.2, 1.2] },
              { "type": "translate", "value": [0, 0, -4] }
            ],
            "children": [
              {
                "mesh_id": "cylinder",
                "material_id": 5
              }
            ]
          }
        ]
      }
    ]
  }
}

=== mwdchang/lightly-rusted/scene01.json
{
  "description": "Scene 01",
  "environment": {
    "background": [0, 0.0, 0],
    "ambient_light": [0.2, 0.2, 0.2],
    "camera_position": [0, 0, 10],
    "camera_target": [0, 0, 0],
    "shadows": true,
    "reflections": true,
    "refractions": true,
    "secondary_ray_eps": 0.0275
  },
  "point_lights": [
    {
      "position": [0, 80, 0],
      "intensity": [500.0, 500.0, 500.0]
    },
    {
      "position": [0, 5, 10],
      "intensity": [500.0, 500.0, 500.0]
    }
  ],
  "materials": [
    {
      "albedo": [0.3, 0.3, 0.3],
      "shine": 0,
      "specular": 0.0,
      "reflectivity": 0.1,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [1.0, 1.0, 0.0],
      "shine": 0.0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.0, 0.9, 0.9],
      "shine": 500.0,
      "specular": 0.1,
      "reflectivity": 0.2,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "texture": "polka",
      "shine": 0.0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.5, 0.5, 0.5],
      "shine": 200.0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.8,
      "ior": 1.13
    },
    {
      "albedo": [0.1, 0.6, 0.1],
      "shine": 0.0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    }
  ],
  "root": {
    "children": [
      {
        "transforms": [
          { "type": "scale", "value": [50.0, 0.05, 50.0] },
          { "type": "translate", "value": [0, -5, 0] }
        ],
        "children": [
          {
            "mesh_id": "cube",
            "material_id": 0
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [13.0, 13.0, 11.0] },
          { "type": "rotate_y", "value": [0.5] },
          { "type": "rotate_x", "value": [1.3] },
          { "type": "translate", "value": [-3, 9, -18] }
        ],
        "children": [
          {
            "mesh_id": "torus",
            "material_id": 1
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [70.0, 70.0, 70.0] },
          { "type": "rotate_y", "value": [0.7]},
          { "type": "translate", "value": [-3, -2, -18] }
        ],
        "children": [
          {
            "mesh_id": "bunny",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [6.0, 6.0, 6.0] },
          { "type": "translate", "value": [9, -2, -16] }
        ],
        "children": [
          {
            "mesh_id": "sphere",
            "material_id": 3
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [2.0, 0.50, 0.10] },
          { "type": "rotate_x", "value": [0.2]},
          { "type": "rotate_y", "value": [-0.4]},
          { "type": "translate", "value": [1.0, -1.0, 6.8] }
        ],
        "children": [
          {
            "mesh_id": "cube",
            "material_id": 4
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [0.5, 2.0, 0.5] },
          { "type": "translate", "value": [2.5, -3.0, 3.5] }
        ],
        "children": [
          {
            "mesh_id": "cone",
            "material_id": 5
          }
        ]
      }

    ]
  }
}

=== mwdchang/lightly-rusted/examples/csg.json
{
  "description": "CSG example",
  "environment": {
    "background": [0, 0.0, 0],
    "ambient_light": [0.2, 0.2, 0.2],
    "camera_position": [0, 0, 10],
    "camera_target": [0, 0, 0],
    "shadows": false,
    "reflections": true,
    "refractions": false,
    "secondary_ray_eps": 0.0275
  },
  "point_lights": [
    {
      "position": [0, 50, 0],
      "intensity": [2500.0, 2500.0, 2500.0]
    },
    {
      "position": [0, 0, 30],
      "intensity": [500.0, 500.0, 500.0]
    }

  ],
  "materials": [
    {
      "albedo": [0.6, 0.6, 0.6],
      "shine": 5000,
      "specular": 0.01,
      "reflectivity": 0.5,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [1.0, 0.0, 0.0],
      "shine": 500.0,
      "specular": 0.5,
      "reflectivity": 0.3,
      "transparency": 0.0,
      "ior": 1
    },
    {
      "albedo": [0.0, 1.0, 0.0],
      "shine": 100.0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "transparency": 0.0,
      "ior": 1
    }
  ],
  "root": {
    "children": [
      {
        "transforms": [
          { "type": "scale", "value": [50.0, 0.05, 50.0] },
          { "type": "translate", "value": [0, -4, 0] }
        ],
        "children": [
          {
            "mesh_id": "cube",
            "material_id": 0
          }
        ]
      },
      {
        "node_type": "csg_difference",
        "transforms": [
          { "type": "rotate_x", "value": [1] },
          { "type": "rotate_y", "value": [1] },
          { "type": "translate", "value": [-4.0, 0.0, -2.0] }
        ],
        "children": [
          {
            "transforms": [
              { "type": "scale", "value": [2.0, 2.0, 2.0] }
            ],
            "mesh_id": "cube",
            "material_id": 1
          },
          {
            "transforms": [
              { "type": "scale", "value": [2.3, 2.3, 2.3] }
            ],
            "mesh_id": "sphere",
            "material_id": 2
          }
        ]
      },
      {
        "node_type": "csg_difference",
        "transforms": [
          { "type": "rotate_x", "value": [0.25] },
          { "type": "rotate_y", "value": [-0.55] },
          { "type": "translate", "value": [4.0, 0.0, -2.0] }
        ],
        "children": [
          {
            "transforms": [
              { "type": "scale", "value": [2.5, 2.5, 2.5] }
            ],
            "mesh_id": "sphere",
            "material_id": 2
          },
          {
            "transforms": [
              { "type": "scale", "value": [2.0, 2.0, 2.0] }
            ],
            "mesh_id": "cube",
            "material_id": 1
          }
        ]
      }
    ]
  }
}
